create chore to install go lint tools; add them to lint job

diff --git a/taskfile.yml b/taskfile.yml
--- a/taskfile.yml
+++ b/taskfile.yml
@@ -27,6 +27,7 @@ tasks:
       - task: imgbuild-apply-branch-protection
       - task: imgbuild-generate-ci-config
       - task: imgbuild-generate-taskfile
+      - task: imgbuild-manage-go-lint-tools
   imgbuild-apply:
     cmds:
       - task: imgbuild-apply-branch-protection
@@ -166,11 +167,59 @@ tasks:
               echo "Tagged ${tag}"
             done
           fi
+  imgbuild-manage:
+    cmds:
+      - task: imgbuild-manage-go-lint-tools
+  imgbuild-manage-go-lint-tools:
+    dir: '{{.ROOT_DIR}}/manage-go-lint-tools'
+    deps:
+      - imgrefs-manage-go-lint-tools
+    cmds:
+      - cmd: |-
+          set -euo pipefail
+
+          if command -v podman >/dev/null 2>&1; then
+            # Podman for building locally or in Tatsu CI
+            builder=podman
+          elif command -v docker >/dev/null 2>&1; then
+            # Docker for building in Circle CI
+            builder=docker
+          else
+            echo "Cannot find Podman or Docker" >&2
+            exit 1
+          fi
+
+          opts=(
+          	-f "Containerfile"
+          )
+
+          # Populate args if a file exists (Podman supports --build-arg-file, but Docker does not)
+          if [[ -f argfile.conf ]]; then
+            while read arg; do
+              k=$(cut -d = -f 1 <<<"$arg")
+              v=$(cut -d = -f 2- <<<"$arg")
+              opts+=("--build-arg" "$k=$v")
+            done <<< "$(cat argfile.conf | grep -v '^#' | grep '=')"
+          fi
+
+          # First build to get visible logs
+          $builder build "${opts[@]}" .
+
+          # Second (cached) build to get the image ID
+          img=$($builder build "${opts[@]}" -q .)
+
+          if [[ -f .imgrefs ]]; then
+            cat .imgrefs | while read tag; do
+              $builder tag "$img" "${tag}"
+              echo "Tagged ${tag}"
+            done
+          fi
   imgpush:
     cmds:
       - task: imgpush-apply-branch-protection
       - task: imgpush-generate-ci-config
       - task: imgpush-generate-taskfile
+      - task: imgpush-manage-go-lint-tools
   imgpush-apply:
     cmds:
       - task: imgpush-apply-branch-protection
@@ -262,11 +311,43 @@ tasks:
             echo "No .imgrefs file - nothing will be pushed"
             exit 1
           fi
+  imgpush-manage:
+    cmds:
+      - task: imgpush-manage-go-lint-tools
+  imgpush-manage-go-lint-tools:
+    dir: '{{.ROOT_DIR}}/manage-go-lint-tools'
+    deps:
+      - imgrefs-manage-go-lint-tools
+    cmds:
+      - cmd: |-
+          set -euo pipefail
+
+          if command -v podman >/dev/null 2>&1; then
+            # Podman for building locally or in Tatsu CI
+            builder=podman
+          elif command -v docker >/dev/null 2>&1; then
+            # Docker for building in Circle CI
+            builder=docker
+          else
+            echo "Cannot find Podman or Docker" >&2
+            exit 1
+          fi
+
+          if [[ -f .imgrefs ]]; then
+            cat .imgrefs | (grep -v "^localhost" || :) | while read tag; do
+              $builder push "${tag}"
+              echo "Pushed ${tag}"
+            done
+          else
+            echo "No .imgrefs file - nothing will be pushed"
+            exit 1
+          fi
   imgrefs:
     cmds:
       - task: imgrefs-apply-branch-protection
       - task: imgrefs-generate-ci-config
       - task: imgrefs-generate-taskfile
+      - task: imgrefs-manage-go-lint-tools
   imgrefs-apply:
     cmds:
       - task: imgrefs-apply-branch-protection
@@ -448,6 +529,67 @@ tasks:
 
           echo "Image refs:"
           cat .imgrefs | grep "." || echo "None"
+  imgrefs-manage:
+    cmds:
+      - task: imgrefs-manage-go-lint-tools
+  imgrefs-manage-go-lint-tools:
+    dir: '{{.ROOT_DIR}}/manage-go-lint-tools'
+    cmds:
+      - cmd: |-
+          set -euo pipefail
+
+          if [[ -f .imgrefs ]] && [[ ${CI+y} == "y" ]]; then
+            echo "Skipping re-computing tags"
+            exit 0
+          fi
+
+          if ! command -v git >/dev/null 2>&1; then
+            echo "Cannot find git" >&2
+            exit 1
+          fi
+
+          if ! git describe --tags >/dev/null 2>&1; then
+            echo "No git tags to descibe" >&2
+            exit 1
+          fi
+
+          if ! grep ".imgrefs" .gitignore >/dev/null 2>&1; then
+            echo ".gitignore must include .imgrefs to use the image builder tasks" >&2
+            exit 1
+          fi
+
+          img_name=$( (grep "LABEL image.name=" Containerfile || echo) | head -n 1 | cut -d '=' -f 2-)
+          img_registry=$( (grep "LABEL image.registry=" Containerfile || echo) | head -n 1 | cut -d '=' -f 2-)
+
+          version=$(git describe --tags)
+          is_exact_tag=$(git describe --tags --exact-match >/dev/null 2>&1 && echo y || echo n)
+          major_version=$(echo "${version}" | cut -d '.' -f 1)
+          latest_version_overall=$(git tag -l | sort -r -V | head -n 1)
+          latest_version_within_major=$(git tag -l | grep "^${major_version}" | sort -r -V | head -n 1)
+
+          echo -n "" > .imgrefs
+
+          if [[ ! -z "$img_name" ]]; then
+            echo "localhost/${img_name}" >> .imgrefs
+            echo "localhost/${img_name}:${version}" >> .imgrefs
+
+            if [[ ! -z "$img_registry" ]] && [[ ${CI+y} == "y" ]]; then
+              echo "${img_registry}/${img_name}:${version}" >> .imgrefs
+
+              if [[ "${is_exact_tag}" == "y" ]] && [[ "${version}" == "${latest_version_within_major}" ]]; then
+                echo "${img_registry}/${img_name}:${major_version}" >> .imgrefs
+              fi
+
+              if [[ "${is_exact_tag}" == "y" ]] && [[ "${version}" == "${latest_version_overall}" ]]; then
+                echo "${img_registry}/${img_name}:latest" >> .imgrefs
+              fi
+            fi
+          else
+            echo "Warning: no image name label; image will not be tagged" >&2
+          fi
+
+          echo "Image refs:"
+          cat .imgrefs | grep "." || echo "None"
   lint:
     cmds:
       - task: lint-go-generate-ci-config
@@ -460,22 +602,76 @@ tasks:
     dir: '{{.ROOT_DIR}}/generate-ci-config'
     cmds:
       - cmd: |-
+          exit_code=0
+
+          # gofmt
           fmt_diff=$(gofmt -e -s -d $(go list -f '{{ "{{.Dir}}" }}' ./... | grep -v /.go/ | grep -v /vendor/))
           if [[ ! -z "$fmt_diff" ]]; then
-            echo "Format errors:"
+            echo "## gofmt:"
             echo "$fmt_diff"
-            exit 1
+            exit_code=1
           fi
+
+          # staticcheck
+          if grep staticcheck go.mod >/dev/null; then
+          	staticcheck=$(go tool staticcheck -checks inherit,+ST1003,+ST1016 ./... || true)
+
+          	if [[ ! -z "$staticcheck" ]]; then
+          		echo "## staticcheck:"
+          		echo "$staticcheck"
+          		exit_code=1
+          	fi
+          fi
+
+          # errcheck
+          if grep errcheck go.mod >/dev/null; then
+          	errcheck=$(go tool errcheck -ignoregenerated ./... || true)
+
+          	if [[ ! -z "$errcheck" ]]; then
+          		echo "## errcheck:"
+          		echo "$errcheck"
+          		exit_code=1
+          	fi
+          fi
+
+          exit $exit_code
   lint-go-generate-taskfile:
     dir: '{{.ROOT_DIR}}/generate-taskfile'
     cmds:
       - cmd: |-
+          exit_code=0
+
+          # gofmt
           fmt_diff=$(gofmt -e -s -d $(go list -f '{{ "{{.Dir}}" }}' ./... | grep -v /.go/ | grep -v /vendor/))
           if [[ ! -z "$fmt_diff" ]]; then
-            echo "Format errors:"
+            echo "## gofmt:"
             echo "$fmt_diff"
-            exit 1
+            exit_code=1
           fi
+
+          # staticcheck
+          if grep staticcheck go.mod >/dev/null; then
+          	staticcheck=$(go tool staticcheck -checks inherit,+ST1003,+ST1016 ./... || true)
+
+          	if [[ ! -z "$staticcheck" ]]; then
+          		echo "## staticcheck:"
+          		echo "$staticcheck"
+          		exit_code=1
+          	fi
+          fi
+
+          # errcheck
+          if grep errcheck go.mod >/dev/null; then
+          	errcheck=$(go tool errcheck -ignoregenerated ./... || true)
+
+          	if [[ ! -z "$errcheck" ]]; then
+          		echo "## errcheck:"
+          		echo "$errcheck"
+          		exit_code=1
+          	fi
+          fi
+
+          exit $exit_code
   lintfix:
     cmds:
       - task: lintfix-go-generate-ci-config
