update taskfile

diff --git a/taskfile.yml b/taskfile.yml
--- a/taskfile.yml
+++ b/taskfile.yml
@@ -34,6 +34,7 @@ tasks:
       - task: imgbuild-applybranchprotection
       - task: imgbuild-generatetasksandci
       - task: imgbuild-managegotools
+      - task: imgbuild-rewritedebianversions
   imgbuild-applybranchprotection:
     dir: '{{.ROOT_DIR}}/apply-branch-protection'
     deps:
@@ -166,11 +167,56 @@ tasks:
               echo "Tagged ${tag}"
             done
           fi
+  imgbuild-rewritedebianversions:
+    dir: '{{.ROOT_DIR}}/rewrite-debian-versions'
+    deps:
+      - imgrefs-rewritedebianversions
+    cmds:
+      - cmd: |-
+          set -euo pipefail
+
+          if command -v podman >/dev/null 2>&1; then
+            # Podman for building locally or in Tatsu CI
+            builder=podman
+          elif command -v docker >/dev/null 2>&1; then
+            # Docker for building in Circle CI
+            builder=docker
+          else
+            echo "Cannot find Podman or Docker" >&2
+            exit 1
+          fi
+
+          opts=(
+          	-f "Containerfile"
+          )
+
+          # Populate args if a file exists (Podman supports --build-arg-file, but Docker does not)
+          if [[ -f argfile.conf ]]; then
+            while read arg; do
+              k=$(cut -d = -f 1 <<<"$arg")
+              v=$(cut -d = -f 2- <<<"$arg")
+              opts+=("--build-arg" "$k=$v")
+            done <<< "$(cat argfile.conf | grep -v '^#' | grep '=')"
+          fi
+
+          # First build to get visible logs
+          $builder build "${opts[@]}" .
+
+          # Second (cached) build to get the image ID
+          img=$($builder build "${opts[@]}" -q .)
+
+          if [[ -f .task-meta-imgrefs ]]; then
+            cat .task-meta-imgrefs | while read tag; do
+              $builder tag "$img" "${tag}"
+              echo "Tagged ${tag}"
+            done
+          fi
   imgpush:
     cmds:
       - task: imgpush-applybranchprotection
       - task: imgpush-generatetasksandci
       - task: imgpush-managegotools
+      - task: imgpush-rewritedebianversions
   imgpush-applybranchprotection:
     dir: '{{.ROOT_DIR}}/apply-branch-protection'
     deps:
@@ -255,11 +301,40 @@ tasks:
             echo "No .task-meta-imgrefs file - nothing will be pushed"
             exit 1
           fi
+  imgpush-rewritedebianversions:
+    dir: '{{.ROOT_DIR}}/rewrite-debian-versions'
+    deps:
+      - imgrefs-rewritedebianversions
+    cmds:
+      - cmd: |-
+          set -euo pipefail
+
+          if command -v podman >/dev/null 2>&1; then
+            # Podman for building locally or in Tatsu CI
+            builder=podman
+          elif command -v docker >/dev/null 2>&1; then
+            # Docker for building in Circle CI
+            builder=docker
+          else
+            echo "Cannot find Podman or Docker" >&2
+            exit 1
+          fi
+
+          if [[ -f .task-meta-imgrefs ]]; then
+            cat .task-meta-imgrefs | (grep -v "^localhost" || :) | while read tag; do
+              $builder push "${tag}"
+              echo "Pushed ${tag}"
+            done
+          else
+            echo "No .task-meta-imgrefs file - nothing will be pushed"
+            exit 1
+          fi
   imgrefs:
     cmds:
       - task: imgrefs-applybranchprotection
       - task: imgrefs-generatetasksandci
       - task: imgrefs-managegotools
+      - task: imgrefs-rewritedebianversions
   imgrefs-applybranchprotection:
     dir: '{{.ROOT_DIR}}/apply-branch-protection'
     cmds:
@@ -378,6 +453,64 @@ tasks:
           cat .task-meta-imgrefs | grep "." || echo "None"
   imgrefs-managegotools:
     dir: '{{.ROOT_DIR}}/manage-go-tools'
+    cmds:
+      - cmd: |-
+          set -euo pipefail
+
+          if [[ -f .task-meta-imgrefs ]] && [[ ${CI+y} == "y" ]]; then
+            echo "Skipping re-computing tags"
+            exit 0
+          fi
+
+          if ! command -v git >/dev/null 2>&1; then
+            echo "Cannot find git" >&2
+            exit 1
+          fi
+
+          if ! git describe --tags >/dev/null 2>&1; then
+            echo "No git tags to descibe" >&2
+            exit 1
+          fi
+
+          if ! grep ".task-meta-*" .gitignore >/dev/null 2>&1; then
+            echo ".gitignore must include .task-meta-* to use the image builder tasks" >&2
+            exit 1
+          fi
+
+          img_name=$( (grep "LABEL image.name=" Containerfile || echo) | tail -n 1 | cut -d '=' -f 2-)
+          img_registry=$( (grep "LABEL image.registry=" Containerfile || echo) | tail -n 1 | cut -d '=' -f 2-)
+
+          version=$(git describe --tags)
+          is_exact_tag=$(git describe --tags --exact-match >/dev/null 2>&1 && echo y || echo n)
+          major_version=$(echo "${version}" | cut -d '.' -f 1)
+          latest_version_overall=$(git tag -l | sort -V | tail -n 1)
+          latest_version_within_major=$(git tag -l | grep "^${major_version}" | sort -V | tail -n 1)
+
+          echo -n "" > .task-meta-imgrefs
+
+          if [[ ! -z "$img_name" ]]; then
+            echo "localhost/${img_name}" >> .task-meta-imgrefs
+            echo "localhost/${img_name}:${version}" >> .task-meta-imgrefs
+
+            if [[ ! -z "$img_registry" ]] && [[ ${CI+y} == "y" ]]; then
+              echo "${img_registry}/${img_name}:${version}" >> .task-meta-imgrefs
+
+              if [[ "${is_exact_tag}" == "y" ]] && [[ "${version}" == "${latest_version_within_major}" ]]; then
+                echo "${img_registry}/${img_name}:${major_version}" >> .task-meta-imgrefs
+              fi
+
+              if [[ "${is_exact_tag}" == "y" ]] && [[ "${version}" == "${latest_version_overall}" ]]; then
+                echo "${img_registry}/${img_name}:latest" >> .task-meta-imgrefs
+              fi
+            fi
+          else
+            echo "Warning: no image name label; image will not be tagged" >&2
+          fi
+
+          echo "Image refs:"
+          cat .task-meta-imgrefs | grep "." || echo "None"
+  imgrefs-rewritedebianversions:
+    dir: '{{.ROOT_DIR}}/rewrite-debian-versions'
     cmds:
       - cmd: |-
           set -euo pipefail
