remove test tasks

diff --git a/taskfile.yml b/taskfile.yml
--- a/taskfile.yml
+++ b/taskfile.yml
@@ -141,10 +141,22 @@ tasks:
           cat .imgrefs | grep "." || echo "None"
   lint:
     cmds:
+      - task: lint-go-generate-ci-config
       - task: lint-go-generate-taskfile
   lint-go:
     cmds:
+      - task: lint-go-generate-ci-config
       - task: lint-go-generate-taskfile
+  lint-go-generate-ci-config:
+    dir: '{{.ROOT_DIR}}/generate-ci-config'
+    cmds:
+      - cmd: |-
+          lint_diff=$(gofmt -e -s -d .)
+          if [[ ! -z "$lint_diff" ]]; then
+            echo "Lint errors:"
+            echo "$lint_diff"
+            exit 1
+          fi
   lint-go-generate-taskfile:
     dir: '{{.ROOT_DIR}}/generate-taskfile'
     cmds:
@@ -157,21 +169,17 @@ tasks:
           fi
   lintfix:
     cmds:
+      - task: lintfix-go-generate-ci-config
       - task: lintfix-go-generate-taskfile
   lintfix-go:
     cmds:
+      - task: lintfix-go-generate-ci-config
       - task: lintfix-go-generate-taskfile
+  lintfix-go-generate-ci-config:
+    dir: '{{.ROOT_DIR}}/generate-ci-config'
+    cmds:
+      - cmd: gofmt -s -w .
   lintfix-go-generate-taskfile:
     dir: '{{.ROOT_DIR}}/generate-taskfile'
     cmds:
       - cmd: gofmt -s -w .
-  test:
-    cmds:
-      - task: test-go-generate-taskfile
-  test-go:
-    cmds:
-      - task: test-go-generate-taskfile
-  test-go-generate-taskfile:
-    dir: '{{.ROOT_DIR}}/generate-taskfile'
-    cmds:
-      - cmd: go test ./...
