add img push task, remove jq dependency

diff --git a/taskfile.yml b/taskfile.yml
--- a/taskfile.yml
+++ b/taskfile.yml
@@ -7,6 +7,9 @@ tasks:
     dir: '{{.ROOT_DIR}}/generate-taskfile'
     cmds:
       - cmd: |2
+          set -euo pipefail
+
+
           # Podman or Docker?
           if command -v podman >/dev/null 2>&1; then
             builder=podman
@@ -14,8 +17,17 @@ tasks:
             builder=docker
           else
             echo "Cannot find Podman or Docker installed - image will not be built" >&2
-          	exit 1
+            exit 1
           fi
+
+          img_name=$( (grep "LABEL image.name=" Containerfile || echo) | head -n 1 | cut -d '=' -f 2-)
+          img_registry=$( (grep "LABEL image.registry=" Containerfile || echo) | head -n 1 | cut -d '=' -f 2-)
+          if git describe --tags >/dev/null 2>&1; then
+            version=":"$(git describe --tags)
+          else
+            version=""
+          fi
+
 
           # First build to get visible logs
           $builder build . -f Containerfile
@@ -23,18 +35,57 @@ tasks:
           # Second (cached) build to get the image ID
           img=$($builder build -q . -f Containerfile)
 
-          img_name=$($builder inspect $img | jq -rc '.[0].Config.Labels["image.name"]')
-          img_registry=$($builder inspect $img | jq -rc '.[0].Config.Labels["image.registry"]')
-          if [[ ! -z  "$img_name" ]]; then
-            $builder tag "$img" "$img_name"
-          	echo "Tagged $img_name"
+          if [[ ! -z "$img_name" ]]; then
+            $builder tag "$img" "localhost/${img_name}${version}"
+            echo "Tagged localhost/${img_name}${version}"
 
-          	if [[ ! -z "$img_registry" ]]; then
-          		$builder tag "$img" "$img_registry/$img_name"
-          		echo "Tagged $img_registry/$img_name"
-          	fi
+            if [[ ! -z "$img_registry" ]]; then
+              $builder tag "$img" "${img_registry}/${img_name}${version}"
+              echo "Tagged ${img_registry}/${img_name}${version}"
+            fi
           else
-            echo "Warning: no image name detected; this image has not been labelled" >&2
+            echo "Warning: no image name label; this image has not been tagged" >&2
+          fi
+  img-push:
+    cmds:
+      - task: img-push-generate-taskfile
+  img-push-generate-taskfile:
+    dir: '{{.ROOT_DIR}}/generate-taskfile'
+    cmds:
+      - cmd: |2
+          set -euo pipefail
+
+
+          # Podman or Docker?
+          if command -v podman >/dev/null 2>&1; then
+            builder=podman
+          elif command -v docker >/dev/null 2>&1; then
+            builder=docker
+          else
+            echo "Cannot find Podman or Docker installed - image will not be built" >&2
+            exit 1
+          fi
+
+          img_name=$( (grep "LABEL image.name=" Containerfile || echo) | head -n 1 | cut -d '=' -f 2-)
+          img_registry=$( (grep "LABEL image.registry=" Containerfile || echo) | head -n 1 | cut -d '=' -f 2-)
+          if git describe --tags >/dev/null 2>&1; then
+            version=":"$(git describe --tags)
+          else
+            version=""
+          fi
+
+
+          if [[ "$img_name" == "" ]]; then
+            echo "Cannot determine image name - image will not be pushed" >&2
+            exit 1
+          elif [[ "$img_registry" == "" ]]; then
+            echo "Cannot determine image registry - image will not be pushed" >&2
+            exit 1
+          elif [[ "$version" == "" ]]; then
+            echo "Cannot determine image version - image will not be pushed" >&2
+            exit 1
+          else
+            $builder push "${img_registry}/${img_name}${version}"
           fi
   lint:
     cmds:
